name = "stremur"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/cloudflare"

[vars]
NEXT_PUBLIC_CONVEX_URL = "https://laudable-jackal-942.convex.cloud"
